# Generated by Django 4.2.4 on 2023-08-10 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_lister', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destinations',
            new_name='Destination',
        ),
    ]
